modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="chunkbychunk"
version="1.0.4"
displayName="ChunkByChunk"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unlockable-chunks"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman318"
description="Play the Game 1 Chuck at a Time, spend XP to Unlock new Chunks"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.chunkbychunk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration