modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="villager_inventory"
version="1.0.3"
displayName="Villager Inventory"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villager-inventory"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman318"
description="Adds a GUI for the Inventory that Villagers have, making it much easier to feed them equally for breeding purposes."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.villager_inventory]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.villager_inventory]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration