modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="bone_handles"
version="1.0.0"
displayName="Bone Handles"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman318"
description="Adds a Alternative to sticks for the handles of Tools, tools with bone handles will have 1.33x more durability & stick tools can be upgraded with a Bone Template"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bone_handles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration