modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="chunkbychunk"
version="1.0.4"
displayName="Chunk By Chunk"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unlockable-chunks"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman318"
description="Play the Game 1 Chuck at a Time, spend XP to Unlock new Chunks"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.chunkbychunk]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.237,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.chunkbychunk]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration