modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="mob_factions"
version="1.0.0"
displayName="Mob Factions"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-factions"
logoFile="logo.png"
credits="Spiderman31807"
authors="Spiderman318"
description="A fully customiseable faction based attacking system for any mob (that doesn't use a brain instead of goals)"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mob_factions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration